direction: left

"Vanilla": "Vanilla\nMC 1.21.x+"
"CraftBukkit": "CraftBukkit\nMC 1.21.x+"
"Spigot": "Spigot\nMC 1.21.x+"
"Paper": "Paper\nMC 1.21.x+"
"Purpur": "Purpur\nMC 1.21.x+"
"Bukkit (API)": "Bukkit (API)"

"CraftBukkit" -> "Vanilla"
"Spigot" -> "CraftBukkit"
"Paper" -> "Spigot"
"Purpur" -> "Paper"

"CraftBukkit" -> "Bukkit (API)"
"Spigot" -> "Bukkit (API)"
"Paper" -> "Bukkit (API)"
