name: Build & Deploy (D2 → SVG → Pages)

on:
  push:
    branches: [main]
    paths:
      - "main.d2"
      - "main.html"
      - ".github/workflows/pages.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache D2 binary
        id: cache-d2
        uses: actions/cache@v4
        with:
          path: ~/.local/bin/d2
          key: d2-linux-amd64-v0.6.7 # change if you bump D2

      - name: Install D2 CLI (if cache miss)
        if: steps.cache-d2.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.local/bin
          curl -fsSL https://d2lang.com/install.sh | sh -s -- -d ~/.local/bin
          ~/.local/bin/d2 --version

      - name: Build SVG with D2
        run: |
          mkdir -p dist
          ~/.local/bin/d2 --layout elk ./main.d2 ./dist/diagram.svg
          cp ./main.html ./dist/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-24.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
